"""adicionar tabela platform_settings

Revision ID: 36d00854858c
Revises: 846f052cecec
Create Date: 2026-07-22 21:57:08.508940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d00854858c'
down_revision = '846f052cecec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asaas_api_key', sa.String(length=255), nullable=True),
    sa.Column('asaas_environment', sa.String(length=20), server_default='sandbox', nullable=False),
    sa.Column('asaas_webhook_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
