"""adicionar icone de categoria, tag de produto, endereco e horario da loja

Revision ID: 846f052cecec
Revises: d16a64410361
Create Date: 2026-07-22 21:22:39.828286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846f052cecec'
down_revision = 'd16a64410361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=20), server_default='other', nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=40), nullable=True))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_street', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('address_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_neighborhood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_neighborhood')
        batch_op.drop_column('address_number')
        batch_op.drop_column('address_street')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('tag')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
