"""adicionar formas de pagamento aceitas por tenant

Revision ID: 91d319bdabb2
Revises: 36d00854858c
Create Date: 2026-07-22 22:44:45.805296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d319bdabb2'
down_revision = '36d00854858c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accept_pix', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('accept_card', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('accept_cash', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('accept_other', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('accept_other')
        batch_op.drop_column('accept_cash')
        batch_op.drop_column('accept_card')
        batch_op.drop_column('accept_pix')

    # ### end Alembic commands ###
