"""add is_featured and display_order to plans

Revision ID: cebcdf31f318
Revises: e4dd9de475cd
Create Date: 2026-07-23 21:06:23.367972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebcdf31f318'
down_revision = 'e4dd9de475cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('display_order')
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
