"""adicionar campos de integracao com Asaas

Revision ID: d16a64410361
Revises: 26fac63863a6
Create Date: 2026-07-22 18:15:40.045836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16a64410361'
down_revision = '26fac63863a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asaas_payment_id', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('payment_link_url', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_asaas_payment_id'), ['asaas_payment_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asaas_customer_id', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('asaas_customer_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_asaas_payment_id'))
        batch_op.drop_column('payment_link_url')
        batch_op.drop_column('asaas_payment_id')

    # ### end Alembic commands ###
