"""adicionar cor de destaque customizavel do painel admin

Revision ID: e115e2075dec
Revises: 91d319bdabb2
Create Date: 2026-07-22 23:12:54.009385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e115e2075dec'
down_revision = '91d319bdabb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_theme_accent', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.drop_column('admin_theme_accent')

    # ### end Alembic commands ###
