"""adicionar landing_content ao platform_settings

Revision ID: e4dd9de475cd
Revises: 1d3d8f560ee5
Create Date: 2026-07-22 23:57:21.559387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4dd9de475cd'
down_revision = '1d3d8f560ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landing_content', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.drop_column('landing_content')

    # ### end Alembic commands ###
